### PR TITLE
Correct taxonomic error

### PR DESCRIPTION
**Pull request by yvanlebras**
Is it ok for you @erasche to update the webhook ?

### CODE REVIEW

**Comment by bgruening** [comment]
It's a fly? :)

**Comment by yvanlebras** [comment]
Fly is not ok in english ? (sorry I'm a poor breton ;) )

**Comment by erasche** [comment]
Huhhhh.

So the cover picture on https://en.wikipedia.org/wiki/Fly definitely looks like the pictures we've been identifying but I really thought we were identifying bees.

What's the Order/Genus that you're expecting the photos to be of? Just to be sure no translation errors :)

**Comment by yvanlebras** [comment]
So this is _Episyrphus balteatus_ , you will be expert now ;)

**Comment by erasche** [comment]
Neat!

**Comment by yvanlebras** [comment]
So flower flies, or syrphid flies, or hoverflies, Flies / fly is just more generic ;)

**Comment by erasche** [comment]
Added some more links/info.

**Pull request merged**
