### PR TITLE
Update MMOS game ID formatting

### PR DESCRIPTION
**Pull request by yvanlebras**
This will potentially fix the actual issue

### CODE REVIEW

**Comment by yvanlebras** [comment]
A possible fix @erasche

**Comment by erasche** [comment]
Yes!! It works!!!!!

**Comment by bgruening** [comment]
@yvanlebras blogpost? :)

**Comment by yvanlebras** [comment]
ouh yeah!

**Comment by erasche** [comment]
Here's a screenshot for you :)

Screenshot_2019-09-03 Galaxy Europe

**Pull request merged**
